### ISSUE TITLE
Create Partners Page

### ISSUE THREAD

**Issue by hantuzun** [hantuzun/pandemic-volunteers#2]
It should have introductory texts.

A form collecting:
* country-state-city
* type (enum) (?)
    * Public corporation (?)
    * NGO
    * Corporation
    * Group
    * Other (?)
* Institution name
* Contact name
* Email address
* Details (?)

In the DB, we need a Partner and a PartnerStaff models with the following attributes:

Partner:
* country-state-city
* type (enum)
* name

CommunityStaff:
* community_id
* name
* email
* details
* active: boolean, default: true

Noted `(?)` for things I'm not sure of.

**Comment by kopchickm** [comment]
Name it Partners

**Comment by hantuzun** [comment]
I did it.

**Comment by hantuzun** [comment]
Some examples of what kind of organizations we could partner with:

| Name | Type | Description | Scope |
|---|---|---|---|
| [Feed a Doc](https://feedadoc.com/) | Volunteering Organization | Helps healthcare workers with meals, childcare, errands, and more | USA |
| [Five up](https://www.fiveup.org/english) | Volunteering Organization | Connects volunteers with the elderly etc. | Switzerland |
| [COVID-19 Assist](https://doc19.org/clinic/volunteer-faq/) | Volunteering Organization | Seeking volunteer healthcare professionals, students, and retirees to take video calls. | USA |
| [The Do](http://thedo.ca/) | Volunteering Organization | Helps the elderly in various ways | Canada |
| [Calderdale Council Coronavirus Volunteers](https://do-it.org/organisations/calderdale-council-corona-volunteers) | Volunteering Organization | Supporting self-isolating individuals with shopping, remote conversation or dog walking and more | Calderdale, UK |
| [La Porte Country Pandemic Response Committee](https://laporteco.in.gov/departments-online/health-department/pandemic-response/pandemic-response-volunteering/) | Governmental Organization | Looking for volunteers at clinics in such roles: medical screeners, triage, vaccinators, clinic educators, floater | La Porte, USA |
| [Southwest Utah Public Health Department ](http://swuhealth.org/) | Governmental Organization | Trains and mobilizes volunteers for triage and more. [Source](https://www.thespectrum.com/story/news/local/cedar-city/2016/03/13/volunteers-needed-pandemic-training/81695360/) | Southwest Utah, USA |
| [Homerun](https://homerun.co.uk/) | Corporation | Marketplace for various services. (Could  integrate volunteers to their system.) | UK |
| [Bill's Food Center](https://billsfoodcenter.com/) | Corporation | Grocery store. (Could help deliveries.) | Oregon, USA |

**Comment by hantuzun** [comment]
Here're two platforms that are aggregating volunteering organizations and presenting them for the US: 
 * https://www.volunteermatch.org/covid19
 * https://mutualaidhub.org
